"use client";

import { createBrowserClient } from '@/lib/supabase/client';
import { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
import Link from 'next/link';

interface Briefing {
  id: string;
  briefing_date: string;
  market_overview: string;
  asset_summaries: {
    symbol: string;
    name?: string;
    summary: string;
    newsCount: number;
  }[];
  notable_headlines: {
    title: string;
    url: string;
    source: string;
  }[];
  total_news_items: number;
  assets_covered: number;
  llm_model?: string;
  generation_time_ms?: number;
  created_at: string;
}

export default function BriefingDetailPage() {
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [loading, setLoading] = useState(true);
  const router = useRouter();
  const params = useParams();
  const date = params.date as string;

  useEffect(() => {
    const supabase = createBrowserClient();
    
    supabase.auth.getUser().then(async ({ data: { user } }) => {
      if (!user) {
        router.replace('/login');
        return;
      }

      const { data: briefingData, error } = await supabase
        .from('daily_briefings')
        .select('*')
        .eq('user_id', user.id)
        .eq('briefing_date', date)
        .single();

      if (error || !briefingData) {
        console.error('Error fetching briefing:', error);
        setLoading(false);
        return;
      }

      setBriefing(briefingData as Briefing);
      setLoading(false);
    });
  }, [date, router]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-600">Loading briefing...</div>
      </div>
    );
  }

  if (!briefing) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <Link href="/dashboard" className="text-blue-600 hover:text-blue-700 mb-4 inline-block">
            ← Back to Dashboard
          </Link>
          <div className="bg-white rounded-xl shadow-sm p-8 text-center">
            <h1 className="text-xl font-semibold text-gray-900 mb-2">Briefing Not Found</h1>
            <p className="text-gray-600">No briefing exists for {date}</p>
          </div>
        </div>
      </div>
    );
  }

  const formattedDate = new Date(briefing.briefing_date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Link href="/dashboard" className="text-blue-600 hover:text-blue-700 text-sm">
            ← Back to Dashboard
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Briefing Header */}
        <div className="bg-white rounded-xl shadow-sm p-6 mb-6">
          <div className="flex items-center gap-3 mb-2">
            <span className="text-3xl">📈</span>
            <h1 className="text-2xl font-bold text-gray-900">Daily Market Briefing</h1>
          </div>
          <p className="text-gray-600">{formattedDate}</p>
          <div className="flex gap-4 mt-3 text-sm text-gray-500">
            <span>{briefing.total_news_items} news items</span>
            <span>•</span>
            <span>{briefing.assets_covered} assets covered</span>
            {briefing.llm_model && (
              <>
                <span>•</span>
                <span>Generated by {briefing.llm_model}</span>
              </>
            )}
          </div>
        </div>

        {/* Market Overview */}
        {briefing.market_overview && (
          <div className="bg-white rounded-xl shadow-sm p-6 mb-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
              🌍 Market Overview
            </h2>
            <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
              {briefing.market_overview}
            </p>
          </div>
        )}

        {/* Asset Summaries */}
        {briefing.asset_summaries && briefing.asset_summaries.length > 0 && (
          <div className="bg-white rounded-xl shadow-sm p-6 mb-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
              📊 Your Portfolio
            </h2>
            <div className="space-y-4">
              {briefing.asset_summaries.map((asset, index) => (
                <div key={index} className="p-4 bg-gray-50 rounded-lg">
                  <div className="flex items-start gap-3">
                    <span className="font-mono font-bold text-blue-600 text-lg">
                      {asset.symbol}
                    </span>
                    <div className="flex-1">
                      {asset.name && (
                        <div className="text-sm text-gray-500 mb-1">{asset.name}</div>
                      )}
                      <p className="text-gray-700">{asset.summary}</p>
                      <div className="text-xs text-gray-400 mt-2">
                        {asset.newsCount} news {asset.newsCount === 1 ? 'item' : 'items'}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Notable Headlines */}
        {briefing.notable_headlines && briefing.notable_headlines.length > 0 && (
          <div className="bg-white rounded-xl shadow-sm p-6 mb-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
              📰 Notable Headlines
            </h2>
            <ul className="space-y-3">
              {briefing.notable_headlines.map((headline, index) => (
                <li key={index} className="flex items-start gap-2">
                  <span className="text-gray-400 mt-0.5">•</span>
                  <div>
                    <a
                      href={headline.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 hover:text-blue-700 hover:underline"
                    >
                      {headline.title}
                    </a>
                    <span className="text-sm text-gray-500 ml-2">— {headline.source}</span>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Footer */}
        <div className="text-center text-xs text-gray-400 py-4">
          <p>This briefing is for informational purposes only and does not constitute financial advice.</p>
          <p className="mt-1">
            Generated at {new Date(briefing.created_at).toLocaleTimeString()}
            {briefing.generation_time_ms && ` in ${briefing.generation_time_ms}ms`}
          </p>
        </div>
      </main>
    </div>
  );
}
